### ISSUE TITLE
naver news

### ISSUE THREAD

**Issue by Anonymous142** [zpacman/Blockzilla#10]
I know it's a filter only for english websites, but report just for refer..

http://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=001&oid=421&aid=0002987684

in [`news.naver.com`] url, general filter `##.sponsor` break the site form: date and comments' number.

thanks for reading...

**Comment by zpacman** [comment]
Hi, thanks for reporting the issue. Could you please force an update for the Blockzilla list and see if the issue has been fixed?

**Comment by zpacman** [comment]
[Version E01](https://github.com/zpacman/Blockzilla/commit/1bf905dbe97f73ad4ff089c90b91cf5b97a811e2)

**Comment by Anonymous142** [comment]
`news.naver.com#@#.sponsor`
it has been fixed!
Really thank you!
