### ISSUE TITLE
Accidentally suppresses Alibaba captcha

### ISSUE THREAD

**Issue by Pharmhaus-2** [zpacman/Blockzilla#2]
The alibaba filter:
||alibaba.com^$popup,image,media,object,object-subrequest,other,ping,script,stylesheet,subdocument,websocket,xmlhttprequest,third-party

also supresses captchas which might be displayed irregularly on various activities (such as confirm order).
unfortunately I did not copy the address of the captcha when that happend and it won't show me any captcha at the very moment 😢 .

**Comment by zpacman** [comment]
Thank you for reporting the issue.  Can you please force an update in Adblock's preferences and confirm if the issue has been resolved?

**Comment by zpacman** [comment]
I removed the filter you mentioned, although I would like to test a modified version of that filter but I don't have an Alibaba account and can't replicate the issue. If you don't mind, it will be appreciated if you could temporarily add the "Testing" list at the [bottom of this page](https://zpacman.github.io/Blockzilla/) to your Adblocker and test to see if the issue still occurs with the modified filter.

**Comment by Pharmhaus-2** [comment]
Hello,
Thank your for your response. I Updated the filter and subscribed to the beta one. However I did not yet manage to trigger a capcha again. Once I do I will see if it occurs again, and if so post the appropriate image link here.

**Comment by Pharmhaus-2** [comment]
popups for security questions:
https://accounts.alibaba.com//user/company/change_email_security_prompt.htm
https://accounts.alibaba.com//user/organization/manage_person_profile.htm
https://accounts.alibaba.com//user/company/pre_set_security_prompt.htm

**Comment by zpacman** [comment]
Thanks. Please force and update for the beta list, and if you could let me know if the captcha's are now displayed.

**Comment by Pharmhaus-2** [comment]
Looks OK so far.

**Comment by zpacman** [comment]
Great. I have updated Blockzilla, you can remove the beta list from your subscriptions.
