### ISSUE TITLE
started blocking youtube today

### ISSUE THREAD

**Issue by tjwoosta** [zpacman/Blockzilla#3]
I have no knowledge of how this stuff works, but I noticed today that youtube stopped working for me (nothing loads except the top bar)
https://i.imgur.com/3hrGde9.png
https://i.imgur.com/nHbckt5.png

After some time I narrowed it down to the Blockzilla filter subscription in ABP. I disabled the filter and youtube works normally again.

**Comment by Marines20** [comment]
Same happen to me, fix plox.

**Comment by zpacman** [comment]
Fixed. The list will automatically update with the fix, or you can force an update in Adblock's preferences. Thanks for reporting the issue.
