### ISSUE TITLE
Prevents closing pagelets on Facebook Pages

### ISSUE THREAD

**Issue by giogziro95** [zpacman/Blockzilla#6]
### Issue

A filter in this list is preventing pagelets from closing on Facebook Pages.

- Filter: `.com/ads/` ([line 647](https://github.com/zpacman/Blockzilla/blob/master/Blockzilla.txt#L41))
- Affected page: Can't provide, since you should be an admin in order to see them. If you have a Facebook Page, send a message to it for testing; if you don't have one, create a test page and then do it.
- Blocked resource: <pre>`https://www.facebook.com/ads/growth/aymt/xout_survey/`</pre>
- Screenshot:
![facebook pages pagelet](https://cloud.githubusercontent.com/assets/2781117/25754486/747b0aac-31d0-11e7-869f-eb97f042644f.png)

### Solution

Add the following exception rule to the list:

```
@@/ads/growth/aymt/xout_survey/$domain=facebook.com
```

**Comment by zpacman** [comment]
Done, [Version C92](https://github.com/zpacman/Blockzilla/commit/a4ecb42be8ba79fee1da6df9b4649b3004c0401e) Can you please confirm the fix?

**Comment by giogziro95** [comment]
Thanks.

Unfortunately, I think I've made a mistake. It turns out that you need to add two exceptions:

1. `@@/ads/growth/aymt/xout_survey/$domain=facebook.com`
2. `@@/ads/growth/aymt/multi_async_click/$domain=facebook.com`

After that, it works as intended.

**Comment by giogziro95** [comment]
No, wait... Actually, you don't even need to add the first one.

Just add: `@@/ads/growth/aymt/multi_async_click/$domain=facebook.com`.

**Comment by zpacman** [comment]
Done, [Version C93](https://github.com/zpacman/Blockzilla/commit/01e4e6ea521d24e5774af002db5309be3e1461c0)

**Comment by giogziro95** [comment]
Yes, it's fixed now.
