### ISSUE TITLE
Breaks Jobs.GE

### ISSUE THREAD

**Issue by giogziro95** [zpacman/Blockzilla#7]
### Issue

A filter in this list is preventing job ads section from showing up on Jobs.GE, an employment website. People deliberately go to this website to see the job ads. It should be noted, that there are banner ads on the website as well (which _should_ be blocked).

- Filter: `##.ad` ([line 807](https://github.com/zpacman/Blockzilla/blob/master/Blockzilla.txt#L807))
- Affected page: _http://www.jobs.ge/eng/141788/_
- Blocked element CSS selector: `#job > table > tbody > tr > td:nth-child(1) > table.ad`
- Screenshot:
![Jobs.GE](https://cloud.githubusercontent.com/assets/2781117/26409178/def6215c-40b0-11e7-868a-4adc5d630900.png)

### Solution

To be honest, I don't know what the correct solution here is. Sure, you could add an exception for this particular case, but I think other websites with similar purpose could be using the same class name for the section throughout the world; so this wouldn't really solve the problem. One of the solutions could be to check whether the domain and/or title contains the words like "job", "employment", "hire", etc.

**Comment by zpacman** [comment]
Done, Version [D04](https://github.com/zpacman/Blockzilla/commit/5f4cda299b521a7fdcd3a91ae5fcfe345d03fab6) and [D05](https://github.com/zpacman/Blockzilla/commit/b12e7c6b1db7a54339c3d58c2845e08585259a58)

Is everything looking good, is `/img2/*$domain=jobs.ge` blocking anything it shouldn't?

**Comment by giogziro95** [comment]
Looks good. Thanks for adding the filters for the banner ads. 🙂

**Comment by giogziro95** [comment]
I'm using this in my custom filters, removes the ad sidebar as well:

```
jobs.ge###job > table > tbody > tr > td:nth-of-type(n+2)
jobs.ge##.AdBanner
```

The most of the filters are region-specific there; I'll release the list someday when it gets big enough.

Anyway, thank you. 🙂

**Comment by zpacman** [comment]
You're welcome.
