### ISSUE TITLE
Only support Adblock?

### ISSUE THREAD

**Issue by zappe** [zpacman/Blockzilla#9]
I use uMatrix, does the list support that?

**Comment by zpacman** [comment]
Hi. 

Blockzilla is written using the Adblock Plus syntax, and therefore Adblock Plus would be the ideal choice.

However, other popular ad blocking add-ons support the Adblock Plus syntax.
For example: "uBlock Origin and uBlock support the majority of Adblock Plus's filter syntax."

* https://en.wikipedia.org/wiki/UBlock_Origin

It  does not look like uMatrix supports the Adblock Plus syntax, but rather "blocks ads through the use of host file" which Blockzilla is not.

* https://www.wilderssecurity.com/threads/ublock-vs-umatrix.376016/

**Comment by zappe** [comment]
Ok, thanks!
